server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/ead-authuser
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # reflect automatically new alterations to the database
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
